/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.CargosDAO;
import br.com.projeto.model.Util;
import br.com.projeto.model.modelCargos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class FrmCargo extends javax.swing.JFrame {

    /**
     * Creates new form FrmCargo
     */
    public FrmCargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        painelgeral1 = new javax.swing.JTabbedPane();
        painelcadcar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtidcargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomecargo = new javax.swing.JTextField();
        painelconsultacar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacargos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtpesqcar = new javax.swing.JTextField();
        btnpesquisar1 = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnnovoexcluir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Cargos");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/zetta_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        painelgeral1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        txtidcargo.setEditable(false);
        txtidcargo.setBackground(new java.awt.Color(204, 204, 204));
        txtidcargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome Cargo:");

        txtnomecargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout painelcadcarLayout = new javax.swing.GroupLayout(painelcadcar);
        painelcadcar.setLayout(painelcadcarLayout);
        painelcadcarLayout.setHorizontalGroup(
            painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadcarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelcadcarLayout.setVerticalGroup(
            painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadcarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(painelcadcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        painelgeral1.addTab("Cadastro", painelcadcar);

        tabelacargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "CARGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelacargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelacargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacargos);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cargo:");

        txtpesqcar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesqcar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesqcarKeyPressed(evt);
            }
        });

        btnpesquisar1.setText("PESQUISAR");
        btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelconsultacarLayout = new javax.swing.GroupLayout(painelconsultacar);
        painelconsultacar.setLayout(painelconsultacarLayout);
        painelconsultacarLayout.setHorizontalGroup(
            painelconsultacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addGroup(painelconsultacarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesqcar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnpesquisar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelconsultacarLayout.setVerticalGroup(
            painelconsultacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelconsultacarLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(painelconsultacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesquisar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelconsultacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtpesqcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelgeral1.addTab("Consulta Cargos", painelconsultacar);

        btnlimpar.setText("LIMPAR TELA");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnnovoexcluir.setText("EXCLUIR");
        btnnovoexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelgeral1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlimpar)
                .addGap(81, 81, 81)
                .addComponent(btnsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnovoexcluir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelgeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpar)
                    .addComponent(btnsalvar)
                    .addComponent(btneditar)
                    .addComponent(btnnovoexcluir))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        // Limpar tela quando tudo estiver preenchido
        new Util().LimparTela(painelcadcar);
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        //BOTÃO SALVAR CARGO

        if (txtnomecargo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo NOME CARGO é Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            modelCargos obj = new modelCargos();

            obj.setNome(txtnomecargo.getText());

            CargosDAO dao = new CargosDAO();
            dao.cadastrarCargo(obj);

            //limpar tela quando o novo cliente for salvo:
            new Util().LimparTela(painelcadcar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        //BOTÃO EDITAR CARGO
        if (txtnomecargo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo NOME CARGO é Obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            modelCargos obj = new modelCargos();

            obj.setId(Integer.parseInt(txtidcargo.getText()));
            obj.setNome(txtnomecargo.getText());

            CargosDAO dao = new CargosDAO();
            dao.alterarCargo(obj);

            //limpar telaquando tudo for alterado:
            new Util().LimparTela(painelcadcar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnnovoexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoexcluirActionPerformed
        //BOTÃO EXCLUIR CARGO
        try {
            modelCargos obj = new modelCargos();

            obj.setId(Integer.parseInt(txtidcargo.getText()));

            CargosDAO dao = new CargosDAO();
            dao.excluirCargo(obj);

            //limpar tela quando tudo for excluido:
            new Util().LimparTela(painelcadcar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnnovoexcluirActionPerformed

    private void txtpesqcarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesqcarKeyPressed
        // CHAMAR NOME CARGO INSTANTANEAMENTE NA TELA DE CONSULTAR CARGOS:
        String nome = "%" + txtpesqcar.getText() + "%";

        CargosDAO dao = new CargosDAO();
        List<modelCargos> lista = dao.buscaCargoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelacargos.getModel();
        dados.setNumRows(0);

        for (modelCargos c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome()
            });

        }
    }//GEN-LAST:event_txtpesqcarKeyPressed

    private void btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisar1ActionPerformed
        // BOTAO PESQUISAR ABA CONSULTA CARGOS

        String nome = "%" + txtpesqcar.getText() + "%";

        CargosDAO dao = new CargosDAO();
        List<modelCargos> lista = dao.buscaCargoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelacargos.getModel();
        dados.setNumRows(0);

        for (modelCargos c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome()
            });

        }
    }//GEN-LAST:event_btnpesquisar1ActionPerformed

    private void tabelacargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelacargosMouseClicked
        // CLICAR E IR PARA OUTRA ABA DO PAINEL
        painelgeral1.setSelectedIndex(0);
        txtidcargo.setText(tabelacargos.getValueAt(tabelacargos.getSelectedRow(), 0).toString());
        txtnomecargo.setText(tabelacargos.getValueAt(tabelacargos.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tabelacargosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnnovoexcluir;
    private javax.swing.JButton btnpesquisar1;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelcadcar;
    private javax.swing.JPanel painelconsultacar;
    private javax.swing.JTabbedPane painelgeral1;
    private javax.swing.JTable tabelacargos;
    private javax.swing.JTextField txtidcargo;
    private javax.swing.JTextField txtnomecargo;
    private javax.swing.JTextField txtpesqcar;
    // End of variables declaration//GEN-END:variables
}
